Repository njfamirm/lorem-ipsum.ir, pull requests merged in 2023-09, with the labels that each got.

#4 feat: update deployment
  .github/workflows/publish-alwatr-container.yml
  cloud/env/12fy-ws-beta.env
  cloud/env/12fy-ws.env
  cloud/env/lorem-ipsum-ir-ws-beta.env
  cloud/env/lorem-ipsum-ir-ws.env
Labels: enhancement

#3 feat: cleanup & under dev page
  README.md
  package.json
  site/_css/base.css
  site/_data/site.json
  site/_includes/footer.njk
  site/_includes/header.njk
  site/_includes/nav.njk
  site/_includes/section/.gitkeep
  site/_includes/section/feature-grid.njk
  site/_layouts/base.njk
  site/en/about.njk
  site/en/en.json
  site/en/home.njk
  site/fa/about.njk
  site/fa/home.njk
Labels: new-feature

#5 feat: upgrade yarn
  .gitignore
  .yarn/releases/yarn-3.6.3.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: dependencies

#6 feat: add deploy command
  package.json
  yarn.lock
Labels: enhancement

#12 fix: install flags
  .github/workflows/build.yaml
  cloud/Dockerfile
Labels: enhancement

#19 feat: update from base
  .github/workflows/build.yaml
  .github/workflows/dependency-review.yaml
  .github/workflows/publish-alwatr-container.yml
  .github/workflows/sync-labels.yml
  config/esbuild.js
  eleventy.config.cjs
  package.json
  site/_data/env.js
  site/_data/site.json
  site/_feed.njk
  site/_includes/google-analytics.njk
  site/_includes/meta.njk
  site/_js/banner.ts
  site/_js/register-service-worker.ts
  site/_js/script.ts
  site/_js/service-worker.ts
  site/_layouts/base.njk
  site/_robots.njk
  site/_script.njk
  site/_service-worker.njk
  site/_sitemap.njk
  yarn.lock
Labels: enhancement

#22 feat: add header
  site/_css/footer.css
  site/_css/main.css
  site/_includes/footer.njk
  site/_includes/header.njk
  site/_includes/navigation-drawer.njk
  site/_layouts/base.njk
  site/_style.njk
  site/fa/home.njk
Labels: new-feature
